<?php
/**
 * COPYRIGHT (C) 1990-2011 
 * Integrated Corporate Solutions, Inc,
 * Florence, AL 35630
 * 
 * RSS controller to handle RSS Requests
 * 
 * @author ICS, Nathan 
 * @package Controllers
 * 
 */
class rss_controller extends application_controller {

  public $private = array();

	public $privileges = array();
	
	public function index()	{ 
	  
		$this->view->set_content("main","user_login.php");
		$this->view->render_page();
		
	}
  
  public function get_coupon_rss() {
    
    //$this->view->set_content( "main" , "user_login.php" );
    // $this->view->set_content( "alerts" , "notice_alert.php" );//    
    //$this->view->render_page();
    //echo "howdy";
    $day = date( "Ymd" );
    $coupons = new_( "Coupon" );
    $coupons->find( 
                array( 
                       "all"    => "true", 
                       //"where"  => "WHERE active = 'Y' AND approved = 'Y' AND show_date <= '$day' AND end_date >='$day' AND start_date <= '$day' AND exp_date >= '$day' AND user_id <> '3'" 
                       "where"  => "WHERE active = 'Y' AND approved = 'Y' AND show_date <= '$day' AND end_date >='$day' AND start_date <= '$day' AND exp_date >= '$day' AND user_id <> '3'" 
                     ) 
               );
    $this->view->coupons = $coupons->find_all;
    $this->view->set_content("rss","rss_items.php");
    $this->view->render_feed();
    
  }
  
  // same RSS Feed as above but this one includes data from 
  // user id 3 - webmaster@chooseics.com
  public function get_test_rss() {
    
    //$this->view->set_content( "main" , "user_login.php" );
    // $this->view->set_content( "alerts" , "notice_alert.php" );//    
    //$this->view->render_page();
    //echo "howdy";
    $day = date( "Ymd" );
    $coupons = new_( "Coupon" );
    $coupons->find( 
                array( 
                       "all"    => "true", 
                       "where"  => "WHERE active = 'Y' AND approved = 'Y' AND show_date <= '$day' AND end_date >='$day' AND start_date <= '$day' AND exp_date >= '$day'" 
                     ) 
               );
    $this->view->coupons = $coupons->find_all;
    $this->view->set_content("rss","rss_items.php");
    $this->view->render_feed();
    
  }
  
  public function get_hi_rss(){
    $this->view->set_content( "main" , "user_login.php" );
    // $this->view->set_content( "alerts" , "notice_alert.php" );//    
    $this->view->render_page();
  }
  
  public function get_face_rss() {
    $construct = array(
                        'appId'  => '23434049831',
                        'secret' => '374a8ef0c93b20c8697f1a4db8d370f8',
                        'cookie' => true,
                      );
                    
    $fb = new_( "facebook", $construct  );
    
        
//374a8ef0c93b20c8697f1a4db8d370f8
      	
     //  https://login.facebook.com/code_gen.php?api_key=374a8ef0c93b20c8697f1a4db8d370f8&v=1.0


  /**
   * **

    $session = $fb->getSession();
    
    var_dump($session);
    
$news_title = "News Item";
$news_url = "http://shoalschamber.com/m2m/";
$news_img = "http://website.com/m2m/copy_of_rainbow_logo.jpg";
$news_text = "This post was generated by PHP";
$page_id = "147150015351833";  // Facebook Page ID 

$feed_title_template = '{actor} posted {headline}';
$feed_title_data = '{"headline":"' . $news_title . '"}';

$feed_body_template = $news_text;

$feed_image = $news_img;
$feed_image_link = $news_url;

$fb->api_client->feed_publishTemplatizedAction($feed_title_template, $feed_title_data, $feed_body_template, "", $page_id, $feed_image, $feed_image_link);
    ****/
    
    var_dump($fb);
  }

}